#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#


name: Refresh CDN
on:
  push:
  workflow_dispatch:

jobs:
  # https://docs.github.com/cn/actions/learn-github-actions/expressions
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Refresh CDN
        run : |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/docs/parameter.json"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/docs/modules.json"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/docs/models.json"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/docs/loads.json"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/docs/exts.json"
          curl -L "https://purge.jsdelivr.net/gh/wjz304/Redpill_CustomBuild@main/docs/tips.md"

          curl -L "https://cdn.statically.io/gh/wjz304/Redpill_CustomBuild/main/docs/parameter.json"
          curl -L "https://cdn.statically.io/gh/wjz304/Redpill_CustomBuild/main/docs/modules.json"
          curl -L "https://cdn.statically.io/gh/wjz304/Redpill_CustomBuild/main/docs/models.json"
          curl -L "https://cdn.statically.io/gh/wjz304/Redpill_CustomBuild/main/docs/loads.json"
          curl -L "https://cdn.statically.io/gh/wjz304/Redpill_CustomBuild/main/docs/exts.json"
          curl -L "https://cdn.statically.io/gh/wjz304/Redpill_CustomBuild/main/docs/tips.md"
          
